# Generated by Django 5.1.4 on 2024-12-08 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_test', models.CharField(choices=[('1', 'technology'), ('2', 'science'), ('3', 'health'), ('4', 'education'), ('5', 'sports'), ('6', 'entertainment'), ('7', 'politics'), ('8', 'business'), ('9', 'travel'), ('10', 'lifestyle'), ('11', 'food'), ('12', 'environment'), ('13', 'fashion'), ('14', 'history'), ('15', 'music'), ('16', 'movies'), ('17', 'gaming'), ('18', 'art'), ('19', 'literature'), ('20', 'finance')], default='1', max_length=230)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='date',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='blog_api.category'),
            preserve_default=False,
        ),
    ]
