# Generated by Django 5.1.4 on 2024-12-08 17:24

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0002_category_remove_post_date_post_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.AddField(
            model_name='post',
            name='categorys',
            field=models.ManyToManyField(to='blog_api.category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_test',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1', 'technology'), ('2', 'science'), ('3', 'health'), ('4', 'education'), ('5', 'sports'), ('6', 'entertainment'), ('7', 'politics'), ('8', 'business'), ('9', 'travel'), ('10', 'lifestyle'), ('11', 'food'), ('12', 'environment'), ('13', 'fashion'), ('14', 'history'), ('15', 'music'), ('16', 'movies'), ('17', 'gaming'), ('18', 'art'), ('19', 'literature'), ('20', 'finance')], default='1', max_length=230),
        ),
    ]
