# Generated by Django 5.1.4 on 2024-12-08 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0003_remove_post_category_post_categorys_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_test',
        ),
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('electronics', 'Electronics'), ('fashion', 'Fashion'), ('home', 'Home'), ('sports', 'Sports'), ('toys', 'Toys')], default='electronics', max_length=20),
        ),
        migrations.RemoveField(
            model_name='post',
            name='categorys',
        ),
        migrations.AddField(
            model_name='post',
            name='categorys',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog_api.category'),
            preserve_default=False,
        ),
    ]
